---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.grafana.name }}-proxy-{{ .Values.grafana.namespace }}
rules:
  - verbs:
      - create
    apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
  - verbs:
      - create
    apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.grafana.name }}-proxy
  namespace: {{ .Values.grafana.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.grafana.name }}-proxy-{{ .Values.grafana.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.grafana.name }}-sa
    namespace: {{ .Values.grafana.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.grafana.name }}-cluster-monitoring-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
subjects:
  - kind: ServiceAccount
    name: {{ .Values.grafana.name }}-sa
    namespace: {{ .Values.grafana.namespace }}
