apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.grafana.name }}-sa-token
  namespace: {{ .Values.grafana.namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.grafana.name }}-sa
type: kubernetes.io/service-account-token
