{{- if .Values.tenant.enabled }}
apiVersion: maas.opendatahub.io/v1alpha1
kind: Tenant
metadata:
  name: default-tenant
  namespace: models-as-a-service
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,ServerSideApply=true
spec:
  gatewayRef:
    name: {{ .Values.tenant.gatewayRef.name }}
    namespace: {{ .Values.tenant.gatewayRef.namespace }}
  telemetry:
    enabled: {{ .Values.tenant.telemetry.enabled }}
    metrics:
      captureOrganization: {{ .Values.tenant.telemetry.metrics.captureOrganization }}
      captureUser: {{ .Values.tenant.telemetry.metrics.captureUser }}
      captureGroup: {{ .Values.tenant.telemetry.metrics.captureGroup }}
      captureModelUsage: {{ .Values.tenant.telemetry.metrics.captureModelUsage }}
{{- end }}
