apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "benchmarks.fullname" . }}-runner
  namespace: {{ include "benchmarks.namespace" . }}
  labels:
    {{- include "benchmarks.labels" . | nindent 4 }}
