{{- if .Values.connectivityLink.enabled }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.connectivityLink.package }}
  namespace: {{ .Values.connectivityLink.namespace }}
spec:
  name: {{ .Values.connectivityLink.package }}
  channel: {{ .Values.connectivityLink.channel }}
  source: {{ .Values.connectivityLink.source }}
  sourceNamespace: {{ .Values.connectivityLink.sourceNamespace }}
{{- end }}
