{{- if .Values.limitador.exhaustiveTelemetry }}
apiVersion: limitador.kuadrant.io/v1alpha1
kind: Limitador
metadata:
  name: limitador
  namespace: {{ .Values.kuadrant.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  telemetry: exhaustive
{{- end }}
