{{- if .Values.limitador.exhaustiveTelemetry }}
apiVersion: limitador.kuadrant.io/v1alpha1
kind: Limitador
metadata:
  name: limitador
  namespace: {{ .Values.kuadrant.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  telemetry: exhaustive
  replicas: {{ .Values.limitador.replicas }}
  resourceRequirements:
    requests:
      cpu: {{ .Values.limitador.resources.requests.cpu }}
      memory: {{ .Values.limitador.resources.requests.memory }}
    limits:
      cpu: {{ .Values.limitador.resources.limits.cpu }}
      memory: {{ .Values.limitador.resources.limits.memory }}
{{- end }}
