{{- if and .Values.rbac.enabled (eq .Values.mode "llminferenceservice") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.global.name }}-view-role
  namespace: {{ .Values.global.namespace }}
  labels:
    opendatahub.io/dashboard: "true"
rules:
- apiGroups:
  - serving.kserve.io
  resourceNames:
  - {{ .Values.global.name }}
  resources:
  - llminferenceservices
  verbs:
  - get
  - post
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.global.name }}-model-get
  namespace: {{ .Values.global.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.global.name }}-view-role
subjects:
{{- range $tier, $_ := .Values.tiers }}
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:{{ $.Values.llminferenceservice.gateway.name }}-tier-{{ $tier }}
{{- end }}
{{- end }}
