rhoai:
  enabled: true
  namespace: redhat-ods-operator
  channel: stable-3.4
  source: redhat-operators
  sourceNamespace: openshift-marketplace

connectivityLink:
  enabled: true
  namespace: openshift-operators
  channel: stable
  package: rhcl-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace

certManager:
  enabled: false

leaderWorkerSet:
  enabled: true
  namespace: leader-worker-set
  channel: stable-v1.0
  source: redhat-operators
  sourceNamespace: openshift-marketplace
