apiVersion: v1
kind: Secret
metadata:
  name: maas-db-config
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_CONNECTION_URL: "postgresql://{{ .Values.database.user }}:{{ .Values.database.password }}@maas-db.{{ .Values.namespace }}.svc:5432/{{ .Values.database.name }}?sslmode=disable"
