apiVersion: v1
kind: Secret
metadata:
  name: model-registry-db
  namespace: {{ include "model-registry.namespace" . }}
  labels:
    {{- include "model-registry.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
type: Opaque
stringData:
  database-password: {{ .Values.postgresql.password | quote }}
