{{- if .Values.benchmarks.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: benchmarks-runner
  namespace: {{ include "evaluation.namespace" . }}
  labels:
    {{- include "evaluation.labels" . | nindent 4 }}
    app.kubernetes.io/component: benchmarks
{{- end }}
