{{- if .Values.benchmarks.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: benchmarks-ca-bundle
  namespace: {{ include "evaluation.namespace" . }}
  labels:
    {{- include "evaluation.labels" . | nindent 4 }}
    app.kubernetes.io/component: benchmarks
    config.openshift.io/inject-trusted-cabundle: "true"
  annotations:
    config.openshift.io/inject-trusted-cabundle: "true"
{{- end }}
