apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhoai-platform-ops
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/davidseve/rhoai-platform-ops.git
    targetRevision: refactor/audit-ignore-differences
    path: argocd/apps
    helm:
      parameters:
        - name: clusterDomain
          value: apps.ocp.sandbox2930.opentlc.com
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
