repoURL: https://github.com/davidseve/rhoai-platform-ops.git
targetRevision: feat/persistent-tempo-storage

modules:
  maas:
    enabled: true
    models:
      tinyllama-test:
        enabled: true
      tinyllama-fast:
        enabled: true
  observability:
    enabled: true
  evaluation:
    enabled: false
