{{- if .Values.modules.maas.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maas-platform
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: modules/maas/charts/maas-platform
    helm:
      parameters:
        - name: clusterDomain
          value: {{ .Values.clusterDomain }}
        - name: grafana.enabled
          value: "{{ .Values.modules.observability.enabled }}"
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 30
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 15m
  ignoreDifferences:
    - group: dscinitialization.opendatahub.io
      kind: DSCInitialization
      jsonPointers:
        - /spec
{{- end }}
