{{- if and .Values.modules.maas.enabled (index .Values.modules.maas.models "tinyllama-test").enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maas-model
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: modules/maas/charts/maas-model
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: tracing.enabled
          value: "{{ .Values.modules.observability.enabled }}"
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 30
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 15m
{{- end }}
