{{- if .Values.modules.observability.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-grafana
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: modules/observability/charts/grafana
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 30
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 15m
  ignoreDifferences:
    - group: grafana.integreatly.org
      kind: Grafana
      jsonPointers:
        - /spec
{{- end }}
